name: Basic
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Show Project files
        run: ls

      - name: Setup DotNet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Check donet version
        run: dotnet --info

      - name: Restore Packages
        run: dotnet restore

      - name: Build Solution
        run: dotnet build -c Release --no-restore

      - name: Run Tests
        run: dotnet test --no-restore -v normal

      - name: Create Deployment Folder
        run: dotnet publish .\src\Web\RToora.DemoRazorPages.Web.csproj -c Release -o deployment

      - name: Check if folder is present
        run: ls

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deployment

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Artifacts
        uses: actions/download-artifact@v4
        with:
          name: deployment-package

      - name: Publishing
        run: |
          ls
          echo "publishing the artifacts"
