name: Basic
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Show Project files
        run: ls
      - name: Setup DotNet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Check donet version
        run: dotnet --info
